<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;

class Product extends Model
{
    protected $fillable = ['category_id', 'name', 'short_name', 'article', 'price', 'collection_id', 'atribut_id', 'discount_id', 'user_id'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function collection()
    {
        return $this->belongsTo('App\Collection');
    }

    public function atribut()
    {
        return $this->belongsTo('App\Atribut');
    }

    public function discount()
    {
        return $this->belongsTo('App\Discount');
    }

    public function resources()
    {
        return $this->hasMany('App\Resource');
    }

    public static function getUniqueName(UploadedFile $file)
    {
        return $newname = date('Y-m-d') . '_' . time() . '_' . $file->getClientOriginalName();
    }

    public function delete()
    {
        $this->delete();
        parent::delete(); // TODO: Change the autogenerated stub
    }
}
